spring:
  graphql:
    graphiql:
      enabled: true

server:
  port: 8081

keycloak:
  realm: mockcompany
  client:
    id: datadoc-api
    secret: vrwQMc5QHD9Znpi2Per30LTSKZ2YoXuR
  base-url: http://localhost:8080/realms
  protocol: openid-connect
  endpoints:
    token: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/token
    revoke: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/revoke
    logout: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/logout
