spring:
  graphql:
    graphiql:
      enabled: true

server:
  port: 8081


keycloak:
  realm: mockcompany
  tokensUrl: http://localhost:8080/realms/mockcompany/protocol/openid-connect/token
  client: datadoc