spring:
  graphql:
    graphiql:
      enabled: true

server:
  port: 8081

keycloak:
  realm: mockcompany
  client: datadoc
  base-url: http://localhost:8080/realms
  protocol: openid-connect
  endpoints:
    token: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/token
    revoke: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/revoke
