spring:
  graphql:
    graphiql:
      enabled: true

server:
  port: 8081

keycloak:
  realm: ${KEYCLOAK_REALM}
  client:
    id: ${KEYCLOAK_CLIENT_ID}
    secret: ${KEYCLOAK_CLIENT_SECRET}
  base-url: ${KEYCLOAK_BASE_URL}
  protocol: ${KEYCLOAK_PROTOCOL}
  endpoints:
    token: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/token
    revoke: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/revoke
    logout: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/logout
    userInfo: ${keycloak.base-url}/${keycloak.realm}/protocol/${keycloak.protocol}/userinfo
